### ISSUE TITLE
Article Images Issues

### ISSUE THREAD

**Issue by gthaka** [jkariscodes/my-demo-website#1]
Hi,

Nice work. I tested creating an Article and uploaded an image . However, the image link is present but seems not to be uploaded upon saving the Article. (screenshots)
![image](https://user-images.githubusercontent.com/6692971/176840135-993c6145-73b9-48e1-8b45-6745773defb1.png)

![image](https://user-images.githubusercontent.com/6692971/176840567-bc42e961-02a4-4318-b90a-3d447f337e86.png)

**Comment by jkariscodes** [comment]
Fixed in  https://github.com/jkariukidev/my-demo-website/commit/9f933658c10906748b15d627e5ff51144ae5240b

**Comment by jkariscodes** [comment]
Fixed in  https://github.com/jkariukidev/my-demo-website/commit/9f933658c10906748b15d627e5ff51144ae5240b
